In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [ ]:
!pip install langchain_community

In [11]:
!ls

'28tech Lập Trình Python 2024 Từ Cơ Bản Tới Nâng Cao Qua 120 Video Và 300 Bài Tập Thực Hành'
'Advanced RAG + ReRank on using LangChain.ipynb'
 AgriCarbonDEX.docx
'Blockchain (1).drawio.png'
 Blockchain.drawio
 Blockchain.drawio.png
 cfg_node_embeddings.npy
'Copy of RAG-SmartVuln.drawio'
 DACN-MultiAgent-MultiModal-RAG
 data-MLP.ipynb
 detected.evm
 detected.sol
'ERC721-ERC20 (1).gdoc'
 ERC721-ERC20.gdoc
 EtherSolve.jar
'fusion agent.ipynb'
 GATv2-CFG.ipynb
 gatv2_embeddings
 graph.dot
 graph.png
 hello.evm
 hello.sol
 IDPS.drawio
 index.html
 Lab_4.ipynb
 Lab_5-Nhom11.ipynb
 MLP-dts.ipynb
 multiagent_RAG+web_assistant.ipynb
 Multi_agent_with_explanation.ipynb
'[NT522.P21.ANTT.2]Lab2_Nhom11.ipynb'
'Ollama-opensource Phi-3-14b.ipynb'
 output
 PII
'PII data.ipynb'
'PII-masking (1).drawio.png'
 PII-masking.drawio
 PII-masking.drawio.png
 pii_sent_response_done.ipynb
 Proxy.evm
 rag_evaluation.ipynb
 RAG-SmartVuln.drawio
 report.json
'scalm-graph (1).ipynb'
 scalm-graph-cle

In [15]:
!pip install pandas scikit-learn torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 32.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 64.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

#test on detected input by user


## cfg

In [154]:
#process to get evm file
import re
import os
import subprocess

# 1. Cài solc-select (chạy một lần)
!pip install solc-select
!solc-select install 0.8.0  # Cài sẵn một version để thử

#user input is a detected code
contract_code = """
// SPDX-License-Identifier: MIT
pragma solidity ^0.4.17;

contract Solidity_OverflowUnderflow {
    uint8 public balance;

    constructor() public {
        balance = 255; // Maximum value of uint8
    }

    // Increments the balance by a given value
    function increment(uint8 value) public {
        balance += value; // Vulnerable to overflow
    }

    // Decrements the balance by a given value
    function decrement(uint8 value) public {
        balance -= value; // Vulnerable to underflow
    }
}

"""

# 2. Tự động trích xuất phiên bản từ mã Solidity

def extract_version(pragma_str):
    match = re.search(r"pragma\s+solidity\s+\^?([0-9]+\.[0-9]+(?:\.[0-9]+)?)", pragma_str)
    if match:
        return match.group(1)
    else:
        raise ValueError("Solidity version not found in pragma.")

version = extract_version(contract_code)
print(f"Detected Solidity version: {version}")


import re

def extract_contract_name(code: str) -> str:
    match = re.search(r'\bcontract\s+([A-Za-z_][A-Za-z0-9_]*)\b', code)
    if match:
        return match.group(1)
    else:
        raise ValueError("No contract name found in code.")


# 3. Cài và chọn đúng phiên bản với solc-select
# Cài solc version nếu chưa có
!solc-select install {version}

# Chọn đúng version để dùng
!solc-select use {version}

# 4. Ghi mã vào file và compile
with open("detected.sol", "w") as f:
    f.write(contract_code)

#5. Trích tên contract
contract_name = extract_contract_name(contract_code)
print(f"Detected contract name: {contract_name}")

#get evm
!solc --bin-runtime detected.sol -o output --overwrite
!cp output/{contract_name}.bin-runtime detected.evm

!java -jar EtherSolve.jar -c -H detected.evm
!java -jar EtherSolve.jar -r -d -o graph.dot detected.evm
!java -jar EtherSolve.jar -r -j -o report.json detected.evm
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.6.0+cpu.html
!pip install torch_geometric

Installing solc '0.8.0'...
Version '0.8.0' installed.
Detected Solidity version: 0.4.17
Installing solc '0.4.17'...
Version '0.4.17' installed.
Switched global version to 0.4.17
Detected contract name: Solidity_OverflowUnderflow
detected.sol:8:16: Error: Expected identifier, got 'LParen'
    constructor() public {
               ^
cp: cannot stat 'output/Solidity_OverflowUnderflow.bin-runtime': No such file or directory
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at parseTree.Contract.<init>(Contract.java:48)
	at parseTree.Contract.<init>(Contract.java:62)
	at cli.MainCLI.call(MainCLI.java:73)
	at cli.MainCLI.call(MainCLI.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(

In [155]:
import json
import torch
from torch.nn import Embedding
from torch_geometric.data import Data
from torch_geometric.nn import GATv2Conv

# === Step 1: Load CFG JSON ===
with open("report.json") as f:
    cfg_json = json.load(f)

nodes = cfg_json["runtimeCfg"]["nodes"]
edges_raw = cfg_json["runtimeCfg"]["successors"]

# === Step 2: Build opcode vocabulary and encode opcodes ===
opcode_vocab = {}
def opcode_to_index(op):
    if op not in opcode_vocab:
        opcode_vocab[op] = len(opcode_vocab)
    return opcode_vocab[op]

max_op_len = 20
node_features = []

for node in nodes:
    if node["parsedOpcodes"]:
        opcodes = [line.split(":")[1].strip().split()[0]
                   for line in node["parsedOpcodes"].split("\n")]
        opcode_ids = [opcode_to_index(op) for op in opcodes]
        padded = opcode_ids[:max_op_len] + [0] * (max_op_len - len(opcode_ids))
    else:
        padded = [0] * max_op_len
    node_features.append(padded)

x = torch.tensor(node_features, dtype=torch.long)  # [num_nodes, max_op_len]

# === Step 3: Embed opcodes using Embedding layer ===
embed_dim = 16
embed = Embedding(len(opcode_vocab), embed_dim)
x_embed = embed(x).mean(dim=1)  # [num_nodes, embed_dim]

# === Step 4: Convert offset-based edges to index-based ===
offset_to_idx = {node["offset"]: idx for idx, node in enumerate(nodes)}

edge_index = []
for entry in edges_raw:
    src_offset = entry["from"]
    for dst_offset in entry["to"]:
        if src_offset in offset_to_idx and dst_offset in offset_to_idx:
            src_idx = offset_to_idx[src_offset]
            dst_idx = offset_to_idx[dst_offset]
            edge_index.append([src_idx, dst_idx])

edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous()

# === Step 5: Create PyTorch Geometric Data object ===
data = Data(x=x_embed, edge_index=edge_index)
print(data)

# === Step 6: Apply GATv2 ===
gat = GATv2Conv(in_channels=embed_dim, out_channels=32, heads=2)
cfg_vec = gat(data.x, data.edge_index)
# print("GATv2 output shape:", output.shape)


Data(x=[53, 16], edge_index=[2, 80])


In [156]:
cfg_vec.shape

torch.Size([53, 64])

## codebert

In [76]:
import torch
import torchvision

print(torch.__version__)        # → 2.6.0+cu118
print(torch.version.cuda)       # → 11.8
print(torchvision.__version__)  # → 0.18.0+cu118 (hoặc gần đó)

2.6.0+cu124
12.4
0.21.0+cu124


In [157]:
from transformers import RobertaTokenizer, RobertaModel

# Load CodeBERT
tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
model = RobertaModel.from_pretrained("microsoft/codebert-base")

# Tokenize
inputs = tokenizer(contract_code, return_tensors="pt", truncation=True, max_length=512)

# Get hidden states
with torch.no_grad():
    outputs = model(**inputs)

# Use [CLS] token embedding as sentence representation
codebert_vec = outputs.last_hidden_state[:, 0, :]  # shape: [1, 768]. Now embedding is a 768-dimensional vector that represents your entire contract.


In [158]:
print(codebert_vec.shape)


torch.Size([1, 768])


## functional sematics

In [159]:
from openai import OpenAI
import os
os.environ["OPENAI_API_KEY"]="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"
client = OpenAI()

def analyze_funtional_sematics_with_gpt(code):
    """Gửi nội dung file Solidity đến OpenAI GPT-3.5 để phân tích"""



    prompt = f"""
        What is the purpose of the above code snippet? Please
        summarize the answer in one sentence with the following format:
        “Abstract purpose:”.

        Please summarize the functions of the above code snippet in the list
        format without any other explanation: “Detail Behaviors: 1. 2. 3...”

        Here is the file content:
        {code}
                """

    try:
        completion = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "developer", "content": "You are a specialist in Smart Contract analysing, talk like an expert in Smart Contract"},
                {
                        "role": "user",
                        "content": prompt,

                },
            ],
        )
        functional_sematic_of_code = completion.choices[0].message.content

        print("functional sematics of the detected code: ", functional_sematic_of_code)
        return functional_sematic_of_code

    except Exception as e:
        print(f"❌ Lỗi khi gọi OpenAI API: {e}")
        return None  # ✅ safely return None in case of error



In [160]:
# 1. Nhận input từ user
user_query = contract_code
# 2. Tìm Purpose gần nhất với input bằng analyze funtional sematics
functional_sematic_of_code = analyze_funtional_sematics_with_gpt(user_query)

functional sematics of the detected code:  Abstract purpose: Demonstrating vulnerability to integer overflow and underflow in smart contracts.

Detail Behaviors: 
1. Initialize the balance to maximum uint8 value (255).
2. increment(uint8 value) function adds the given value to the balance, vulnerable to overflow.
3. decrement(uint8 value) function subtracts the given value from the balance, vulnerable to underflow.


In [161]:
from sentence_transformers import SentenceTransformer
from langchain.embeddings import HuggingFaceEmbeddings
# Khởi tạo embeddings từ HuggingFace
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

In [162]:
minilm_vec = embeddings.embed_query(functional_sematic_of_code)

In [163]:
minilm_vec


[-0.09040491282939911,
 0.11969856172800064,
 -0.013197259046137333,
 -0.06696122139692307,
 -0.04392675682902336,
 -0.023971274495124817,
 -0.023390578106045723,
 0.13786694407463074,
 -0.025966383516788483,
 0.03325320780277252,
 -0.03791738674044609,
 -0.03299829736351967,
 0.051450882107019424,
 -0.0670013502240181,
 -0.020558364689350128,
 0.009238573722541332,
 -0.011442509479820728,
 0.08554257452487946,
 -0.09227226674556732,
 -0.014043035916984081,
 0.08120373636484146,
 0.04038601741194725,
 -0.09254154562950134,
 0.04287955164909363,
 -0.06114311143755913,
 -0.029519155621528625,
 -0.053836602717638016,
 -0.021838918328285217,
 0.05951584875583649,
 -0.07238473743200302,
 0.03312932699918747,
 0.1157490611076355,
 0.04916222766041756,
 0.021047895774245262,
 -0.07237692922353745,
 0.014219474978744984,
 0.012038336135447025,
 -0.025772906839847565,
 0.03302706032991409,
 0.05074562132358551,
 -0.04352254420518875,
 -0.02142510563135147,
 -0.006665055174380541,
 0.03439128026

## concat

In [164]:
codebert_vec = codebert_vec.squeeze(0).detach().numpy()
cfg_vec = cfg_vec.mean(dim=0).detach().numpy()
minilm_vec = np.array(minilm_vec, dtype=np.float32)


In [165]:
final_embedding = np.concatenate([codebert_vec, minilm_vec, cfg_vec])


In [166]:
print(final_embedding.shape)

(1216,)


# train MLP

In [167]:
# === Load file Excel ===
df = pd.read_excel("embedding for MLP.xlsx")
df = df.dropna(subset=["codebert_embedding", "minilm_embedding", "cfg_embedding"]).reset_index(drop=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [168]:
import pandas as pd
import numpy as np
import ast
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# === Load file Excel ===
# df = pd.read_excel("embedding for MLP.xlsx")
# df = df.dropna(subset=["codebert_embedding", "minilm_embedding", "cfg_embedding"]).reset_index(drop=True)

# === Chuyển từ chuỗi → mảng float ===
def parse_embedding(x):
    return np.array(ast.literal_eval(x), dtype=np.float32)

df["codebert_embedding"] = df["codebert_embedding"].apply(parse_embedding)
df["minilm_embedding"] = df["minilm_embedding"].apply(parse_embedding)
df["cfg_embedding"] = df["cfg_embedding"].apply(parse_embedding)

# === Nối tất cả embedding lại thành 1 vector duy nhất ===
df["combined"] = df.apply(lambda row: np.concatenate([
    row["codebert_embedding"],
    row["minilm_embedding"],
    row["cfg_embedding"]
]), axis=1)

X = np.stack(df["combined"].values)  # Input features

# === Chuẩn hóa label thành số
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df["label"])  # Ground truth labels (0→n)

# === Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# === Chuyển sang Tensor
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

# === Định nghĩa mô hình MLP
class MLP(nn.Module):
    def __init__(self, input_size, num_classes):
        super(MLP, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.model(x)

model = MLP(input_size=X.shape[1], num_classes=len(label_encoder.classes_))

# === Loss + Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# === Train
print("🔁 Training started...")
for epoch in range(120):  # Bạn có thể thay đổi số epoch tùy dataset
    model.train()
    running_loss = 0.0
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"📆 Epoch {epoch+1} - Loss: {running_loss:.4f}")

# === Evaluate
model.eval()
with torch.no_grad():
    outputs = model(X_test_tensor)
    predictions = torch.argmax(outputs, dim=1)
    acc = (predictions == y_test_tensor).sum().item() / len(y_test_tensor)
    print(f"\n✅ Accuracy on test set: {acc * 100:.2f}%")

# === Optional: In ra các label
print("\n📌 Label Mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"{i} → {label}")




🔁 Training started...
📆 Epoch 1 - Loss: 15.0204
📆 Epoch 2 - Loss: 13.6760
📆 Epoch 3 - Loss: 13.2979
📆 Epoch 4 - Loss: 13.1330
📆 Epoch 5 - Loss: 12.8675
📆 Epoch 6 - Loss: 12.4432
📆 Epoch 7 - Loss: 12.6128
📆 Epoch 8 - Loss: 12.0403
📆 Epoch 9 - Loss: 11.5792
📆 Epoch 10 - Loss: 11.5377
📆 Epoch 11 - Loss: 10.7948
📆 Epoch 12 - Loss: 11.1081
📆 Epoch 13 - Loss: 9.9582
📆 Epoch 14 - Loss: 9.3884
📆 Epoch 15 - Loss: 9.4702
📆 Epoch 16 - Loss: 8.3568
📆 Epoch 17 - Loss: 7.9872
📆 Epoch 18 - Loss: 7.3274
📆 Epoch 19 - Loss: 6.5861
📆 Epoch 20 - Loss: 6.0958
📆 Epoch 21 - Loss: 5.6287
📆 Epoch 22 - Loss: 4.7420
📆 Epoch 23 - Loss: 5.3015
📆 Epoch 24 - Loss: 5.1419
📆 Epoch 25 - Loss: 4.5555
📆 Epoch 26 - Loss: 4.2762
📆 Epoch 27 - Loss: 3.5138
📆 Epoch 28 - Loss: 3.6068
📆 Epoch 29 - Loss: 3.2171
📆 Epoch 30 - Loss: 3.0077
📆 Epoch 31 - Loss: 2.8049
📆 Epoch 32 - Loss: 2.7187
📆 Epoch 33 - Loss: 2.4794
📆 Epoch 34 - Loss: 2.7751
📆 Epoch 35 - Loss: 2.0601
📆 Epoch 36 - Loss: 2.2920
📆 Epoch 37 - Loss: 2.0858
📆 Epoch 38 - 

In [169]:
from sklearn.metrics import confusion_matrix, classification_report

# === Confusion Matrix + Classification Report ===
print("\n📊 Confusion Matrix:")
cm = confusion_matrix(y_test_tensor.numpy(), predictions.numpy())
print(cm)

print("\n📈 Classification Report:")
report = classification_report(
    y_test_tensor.numpy(),
    predictions.numpy(),
    target_names=label_encoder.classes_,
    digits=3
)
print(report)



📊 Confusion Matrix:
[[0 1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 4 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0]
 [3 0 0 0 0 1 0 0 7]]

📈 Classification Report:


ValueError: Number of classes, 9, does not match size of target_names, 10. Try specifying the labels parameter

In [170]:
# giả sử bạn đã có 3 embedding:
# - codebert_vec: shape (768,)
# - minilm_vec: shape (384,)
# - cfg_vec: shape (64,)

final_embedding = np.concatenate([codebert_vec, minilm_vec, cfg_vec])
input_tensor = torch.tensor([final_embedding], dtype=torch.float32)

# Dự đoán
model.eval()
with torch.no_grad():
    output = model(input_tensor)
    pred_label_id = torch.argmax(output, dim=1).item()
    label_name = label_encoder.classes_[pred_label_id]
    print(" Predicted label:", label_name)


 Predicted label: arithmetic
